spring:
  application:
    name: shopping-cart-mcp
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart-mcp
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # MCP Server configuration
  ai:
    mcp:
      server:
        type: SYNC
        stdio: true
        name: shopping-cart-server
        version: 1.0.0

  # Critical for STDIO communication
  main:
    web-application-type: none
    banner-mode: log

logging:
  pattern:
    console:
  file:
    name: logs/shopping-cart-mcp.log