server:
  port: 8080
spring:
  application:
    name: shopping-cart-mcp
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping-cart-mcp
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # MCP Server configuration
  ai:
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        type: SYNC
        stdio: false
        name: shopping-cart-server
        version: 1.0.0

logging:
  file:
    name: logs/shopping-cart-mcp.log
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    io.modelcontextprotocol: DEBUG
    org.springframework.ai.mcp: DEBUG